quotes = [
    "The only limit to our realization of tomorrow is our doubts of today.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "In the middle of every difficulty lies opportunity.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "You miss 100% of the shots you don't take.",
    "Whether you think you can or you think you can't, you're right.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "Don't watch the clock; do what it does. Keep going.",
    "Just do it.",
    "The best way to predict the future is to create it.",
    "If you want to live a happy life, tie it to a goal, not to people or things.",
    "Life is what happens when you're busy making other plans.",
    "Your time is limited, so don't waste it living someone else's life.",
    "You only live once, but if you do it right, once is enough.",
    "The purpose of our lives is to be happy.",
    "Get busy living or get busy dying.",
    "You have within you right now, everything you need to deal with whatever the world can throw at you.",
    "Believe you can and you're halfway there.",
    "Dream big and dare to fail.",
    "Act as if what you do makes a difference. It does.",
    "Don't wait. The time will never be just right.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Opportunities don't happen. You create them.",
    "I find that the harder I work, the more luck I seem to have.",
    "The only way to do great work is to love what you do.",
    "If you are not willing to risk the usual, you will have to settle for the ordinary.",
    "Do what you can, with what you have, where you are.",
    "You are never too old to set another goal or to dream a new dream.",
    "What we achieve inwardly will change outer reality.",
    "It is never too late to be what you might have been.",
    "The only person you are destined to become is the person you decide to be.",
    "If you can dream it, you can achieve it.",
    "Everything you've ever wanted is on the other side of fear.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "You can't use up creativity. The more you use, the more you have.",
    "Do not wait to strike till the iron is hot, but make it hot by striking.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "How wonderful it is that nobody need wait a single moment before starting to improve the world.",
    "The best revenge is massive success.",
    "The man who moves a mountain begins by carrying away small stones.",
    "If you keep your eyes on the goal, you can't see the obstacles.",
    "Happiness is not something ready-made. It comes from your own actions.",
    "Keep your face always toward the sunshine—and shadows will fall behind you.",
    "Life isn't about finding yourself. Life is about creating yourself.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Everything has beauty, but not everyone sees it.",
    "You are never too old to set another goal or to dream a new dream.",
    "The mind is everything. What you think you become.",
    "Life is either a daring adventure, or nothing at all.",
    "Limit your 'always' and your 'nevers.'",
    "Nothing is impossible, the word itself says 'I'm possible'!",
    "Success is the sum of small efforts, repeated day in and day out.",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "Challenges are what make life interesting. Overcoming them is what makes life meaningful.",
    "A person who never made a mistake never tried anything new.",
    "Failure is simply the opportunity to begin again, this time more intelligently.",
    "Courage is not the absence of fear, but the triumph over it.",
    "If you can't explain it simply, you don't understand it well enough.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "We may encounter many defeats but we must not be defeated.",
    "You only live once, but if you do it right, once is enough.",
    "Everything you can imagine is real.",
    "The best preparation for tomorrow is doing your best"
]

names = [
"susan",
"frank",
"josh"
]