quotes = [
    "The only limit to our realization of tomorrow is our doubts of today.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "In the middle of every difficulty lies opportunity.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "You miss 100% of the shots you don't take.",
    "Whether you think you can or you think you can't, you're right.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "Don't watch the clock; do what it does. Keep going.",
    "Just do it.",
    "The best way to predict the future is to create it.",
    "If you want to live a happy life, tie it to a goal, not to people or things.",
    "Life is what happens when you're busy making other plans.",
    "Your time is limited, so don't waste it living someone else's life.",
    "You only live once, but if you do it right, once is enough.",
    "The purpose of our lives is to be happy.",
    "Get busy living or get busy dying.",
    "You have within you right now, everything you need to deal with whatever the world can throw at you.",
    "Believe you can and you're halfway there.",
    "Dream big and dare to fail.",
    "Act as if what you do makes a difference. It does.",
    "Don't wait. The time will never be just right.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Opportunities don't happen. You create them.",
    "I find that the harder I work, the more luck I seem to have.",
    "The only way to do great work is to love what you do.",
    "If you are not willing to risk the usual, you will have to settle for the ordinary.",
    "Do what you can, with what you have, where you are.",
    "You are never too old to set another goal or to dream a new dream.",
    "What we achieve inwardly will change outer reality.",
    "It is never too late to be what you might have been.",
    "The only person you are destined to become is the person you decide to be.",
    "If you can dream it, you can achieve it.",
    "Everything you've ever wanted is on the other side of fear.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "You can't use up creativity. The more you use, the more you have.",
    "Do not wait to strike till the iron is hot, but make it hot by striking.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "How wonderful it is that nobody need wait a single moment before starting to improve the world.",
    "The best revenge is massive success.",
    "The man who moves a mountain begins by carrying away small stones.",
    "If you keep your eyes on the goal, you can't see the obstacles.",
    "Happiness is not something ready-made. It comes from your own actions.",
    "Keep your face always toward the sunshine—and shadows will fall behind you.",
    "Life isn't about finding yourself. Life is about creating yourself.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Everything has beauty, but not everyone sees it.",
    "You are never too old to set another goal or to dream a new dream.",
    "The mind is everything. What you think you become.",
    "Life is either a daring adventure, or nothing at all.",
    "Limit your 'always' and your 'nevers.'",
    "Nothing is impossible, the word itself says 'I'm possible'!",
    "Success is the sum of small efforts, repeated day in and day out.",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "Challenges are what make life interesting. Overcoming them is what makes life meaningful.",
    "A person who never made a mistake never tried anything new.",
    "Failure is simply the opportunity to begin again, this time more intelligently.",
    "Courage is not the absence of fear, but the triumph over it.",
    "If you can't explain it simply, you don't understand it well enough.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "We may encounter many defeats but we must not be defeated.",
    "You only live once, but if you do it right, once is enough.",
    "Everything you can imagine is real.",
    "The best preparation for tomorrow is doing your best"
]


girl_names = [
    "Emma", "Olivia", "Ava", "Isabella", "Sophia", "Charlotte", "Mia", "Amelia",
    "Harper", "Evelyn", "Abigail", "Ella", "Scarlett", "Grace", "Chloe", "Lily",
    "Aria", "Ella", "Madison", "Aurora", "Hazel", "Nora", "Zoe", "Stella",
    "Luna", "Ariana", "Violet", "Layla", "Riley", "Savannah", "Addison", "Brooklyn",
    "Bella", "Claire", "Skylar", "Lucy", "Anna", "Camila", "Genesis", "Naomi",
    "Sophie", "Everly", "Maria", "Elena", "Mariah", "Kinsley", "Athena", "Alyssa",
    "Audrey", "Katherine", "Caroline", "Victoria", "Natalie", "Gemma", "Serenity",
    "Peyton", "Allison", "Quinn", "Eliana", "Samantha", "Maya", "Lydia", "Josie",
    "Nina", "Hannah", "Faith", "Margaret", "Daisy", "Lila", "Tessa", "Piper",
    "Skyler", "Reagan", "Cora", "Greta", "Clara", "Sienna", "Kylie", "Juliet",
    "Addilyn", "Taylor", "Jessica", "Autumn", "Kaitlyn", "Phoenix", "Rylee",
    "Sarai", "Emery", "Kendall", "Aubrey", "Brooke", "Leah", "Mackenzie", "Bianca",
    "Selena", "Callie", "Sabrina", "Willa", "Juliana", "Zara"
]

boy_names = [
    "Liam", "Noah", "Oliver", "Elijah", "James", "William", "Benjamin", "Lucas",
    "Henry", "Alexander", "Jackson", "Sebastian", "Ethan", "Michael", "Daniel",
    "Matthew", "Aiden", "Caleb", "Isaac", "Gabriel", "Nathan", "Mason", "Jack",
    "Owen", "Dylan", "Luke", "Samuel", "Jameson", "Ryan", "David", "Anthony",
    "Charles", "Christopher", "Jaxon", "Asher", "Leo", "Thomas", "Eli", "Aaron",
    "Jonathan", "Julian", "Hudson", "Robert", "Christian", "Archer", "Luca",
    "Josiah", "Isaiah", "Adam", "Leonardo", "Nolan", "Jeremiah", "Easton",
    "Colton", "Hunter", "Cooper", "Santiago", "Axel", "Xander", "Carter",
    "Everett", "Micah", "Graham", "Landon", "Max", "Zachary", "Phoenix", "Bennett",
    "Brayden", "James", "Jason", "Jude", "Tristan", "Ryder", "Sawyer", "Elias",
    "Beckett", "Finn", "Luca", "Kai", "Jasper", "Antonio", "Dante", "Maddox",
    "Kaden", "Colin", "Jett", "Rafael", "Kylan", "Freddie", "Simon", "Adriel",
    "Tobias", "Bodhi", "Krew", "Reuben", "Cyrus", "Harrison", "Zane", "Kyran"
]


jokes = [
"Why do programmers prefer dark mode? Because light attracts bugs!",
"How many programmers does it take to change a light bulb? None, that's a hardware problem!",
"Why do Java developers wear glasses? Because they don't see sharp!",
"Why was the developer unhappy at their job? They wanted arrays!",
"What do you call a programmer from Finland? Nerdic!",
"Why do Python programmers prefer using snakes? Because they don’t like class.",
"Why was the computer cold? It left its Windows open!",
"Why did the programmer quit his job? Because he didn't get arrays.",
"How do you comfort a JavaScript bug? You console it.",
"Why was the JavaScript file sad? It didn’t know how to ‘null’ its feelings.",
"What do you call 8 hobbits? A hobbyte!",
"Why did the programmer bring a ladder to work? Because he wanted to reach new heights!",
"Why do programmers hate nature? It has too many bugs.",
"Why did the coder cross the road? To get to the other side of the function!",
"How do you help a JavaScript developer? Just give them a break!",
"What did the Python say when it got stuck in traffic? ‘I can’t take this anymore!’",
"Why do programmers prefer iOS development? Because Android is too buggy!",
"How do you organize a space party? You planet!",
"What do you call a snake that writes code? A pythonista!",
"Why do computers always run slow? Because they don't have much RAM!",
"What’s a programmer’s favorite hangout place? The Foo Bar!",
"Why did the computer go to therapy? It had too many bytes!",
"Why did the developer go broke? Because he lost his domain in the last bid!",
"Why do programmers like nature? It has great arrays!",
"Why don’t programmers like to play hide and seek? Because good luck hiding from the debugger!",
"What do you call an educated adult? A graduate!",
"Why couldn’t the computer take its hat off? Because it had a bad case of CAPS LOCK!",
"What is a computer’s favorite snack? Microchips!",
"What did the computer do at lunchtime? Had a byte!",
"Why did the coder get kicked off the trampoline? He couldn’t handle the bounce!",
"Why did the programmer get glasses? To improve his vision for coding!",
"What did the software engineer say to his girlfriend? ‘You complete me!’",
"Why don’t programmers like the outdoors? Too many bugs!",
"What do you call a computer that sings? A Dell!",
"Why was the developer always calm? Because he had built-in error handling!",
"What do programmers use for a ladder? A recursion!",
"What do you call a programmer who doesn’t use Git? A version-less coder!",
"Why did the developer stay calm during stress tests? Because he knew he was built for heavy loads!",
"Where do programmers store their secrets? In a safe (and secure) array!",
"Why did the programmer fail art class? He didn’t use proper syntax!",
"What do you call a computer that can do math? A calculator!",
"Why did the developer go broke? He needed a ‘byte’!",
"How do you know if a programmer is lying? Their lips are moving!",
"What do you get when you cross a computer and a life guard? A screensaver!",
"How do programmers cheer each other up? They share their ‘code’!",
"What did the code say when it got confused? ‘I’m so lost in syntax!’",
"Why did the cookie go to the developer? Because it needed a cookie-jar!",
"What do you call an algorithm that helps you save time? A time saver!",
"Why was the JavaScript function sad? Because it didn’t have a closure!",
"Why do programmers prefer fish as pets? Because they keep everything in their ‘school’!",
"How does a programmer greet another? ‘Hello, World!’",
"Why don’t programmers like shopping? Because they can’t open a new window!",
"How do you make a computer laugh? You give it a funny chip!",
"What did the student say to the computer? ‘You’ve got all the answers!’",
"Why do robots love to dance? They have great algorithms!",
"What did one programmer say to the other? ‘You’ve got the right code!’",
"Why did the coder break up with his girlfriend? She had too many bugs!",
"What did the Java code say to the Python code? ‘You’re not my type!’"
]
